### ISSUE TITLE
"Use custom audio device" Missing in properties for devices

### ISSUE THREAD

**Issue by HaloMillennium** [dorianmuthig/obs-studio-ftl#2]
![image](https://user-images.githubusercontent.com/29910815/27850979-f58f3abc-6125-11e7-847c-84073dc9124c.png)
![image](https://user-images.githubusercontent.com/29910815/27850985-fa8dc6a0-6125-11e7-9339-814365a72ed7.png)

**Comment by dori4n** [comment]
This is an option available in OBS Studio 19.0.3. The binaries made available here are still OBS Studio 19.0.2 for stability reasons. Please try the build at https://github.com/mixer/obs-studio-ftl/releases/download/v1.0.0/OBS-Studio-19.0.3-FTL-Full-Installer.exe
