### ISSUE TITLE
Library not loaded libjansson.4.dylib

### ISSUE THREAD

**Issue by narcogen** [dorianmuthig/obs-studio-ftl#3]
On MacOS El Capitan. Followed instructions in readme, upgraded Qt to 5.9, upgraded ffmpeg to 3.3. Ran the vanilla OBS installer, then copied over the app.

Receiving this message on launch:

```
Dyld Error Message:
  Library not loaded: /usr/local/opt/jansson/lib/libjansson.4.dylib
```

It may be necessary to run

`brew install jansson
`
For the MacOS installation to function for some users.

**Comment by dori4n** [comment]
I have updated the `README.txt` in the DMG image already. I hope it works well for you. 🙂

**Comment by narcogen** [comment]
Thanks!
